"""add email sent flags to queue_entries

Revision ID: a62ea4deccdc
Revises: 9a62ebe93896
Create Date: 2026-09-06 22:48:37.503394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62ea4deccdc'
down_revision: Union[str, Sequence[str], None] = '9a62ebe93896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_entries', sa.Column('next_email_sent', sa.Boolean(), nullable=True))
    op.add_column('queue_entries', sa.Column('ready_email_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_entries', 'ready_email_sent')
    op.drop_column('queue_entries', 'next_email_sent')
    # ### end Alembic commands ###
