"""change ai_summary column type to JSON in Report table

Revision ID: b87d65b2723a
Revises: a62ea4deccdc
Create Date: 2026-09-15 20:10:17.169284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87d65b2723a'
down_revision: Union[str, Sequence[str], None] = 'a62ea4deccdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'ai_summary',
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=True,
        postgresql_using='ai_summary::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'ai_summary',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='ai_summary::text')
    # ### end Alembic commands ###
