"""make appointment_id constraint nullable on reports

Revision ID: f8800efd99c2
Revises: b87d65b2723a
Create Date: 2026-09-16 19:02:01.134580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8800efd99c2'
down_revision: Union[str, Sequence[str], None] = 'b87d65b2723a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
